@host = http://localhost:3000

###################################################

# ENDPOINT PRINCIPAL DE USUSARIOS #

@Cuentos = http://localhost:3000/api/Stories

### title, description, author, date (12-30-xxxx)
GET {{host}}/api/libros?date=02-05-2023
###
GET {{host}}/api/libros?description=no

###################################################
# EndPoint Para obtener Cuentos #
GET {{Cuentos}}

###################################################
# Cuidado con las comas ( , ) en las llamadas #
# Si no se pone una URl en imagen se pone una en auto #
# End Para agregar cuentos #
POST {{Cuentos}}
Content-Type: application/json

{
    "title": "trots",
    "description": "hombre homosexual, enano, tepiteño",
    "publicationDate": "03/03/2010",
    "imageUrl": ""
}

###################################################
# UUID al final del endpoint con / #
# End Para borrar cuentos #
DELETE {{Cuentos}}/

###################################################
# UUID al final del endpoint con / #
# End Para editar cuentos #
PUT {{Cuentos}}/Pruebas
Content-Type:  application/json

{
    "title": "Editado",
    "description": "Descripcion editada",
    "publicationDate": "2023-05-01",
    "imageUrl": ""
}

###################################################
###################################################

# ENDPOINT PRINCIPAL DE USUSARIOS #
@User = http://localhost:3000/user

###################################################
# EndPoint Para obtener Usuarios #
GET {{User}}

###
GET {{User}}?username=bubueno

###
GET {{User}}?email=txt

###################################################
# Cuidado con las comas ( , ) en las llamadas #
# Todos los campos son requeridos #
# End Para agregar Usuarios #
POST {{User}}
Content-Type: application/json

{
    "username": "algoEjemplo",
    "email": "ejemplo@ejemplo.com",
    "password": "1234"
}

###################################################
# UUID al final del endpoint con / #
# End Para editar usuarios #
PUT {{User}}/
Content-Type: application/json

{
    "username": "Bubu Cambiado",
    "password": "2627"
}

###################################################
# UUID al final del endpoint con / #
# End Para borrar usuarios #
DELETE {{User}}/

###################################################
###################################################

@login = http://localhost:3000/user/login

###
GET {{login}}
x-token: 

###

POST {{login}}
Content-Type: application/json

{
    "email": "bubu@ejemplo.com",
    "password": "2627"
}

################################################
################################################

# Pruebas para google auth #

@google = http://localhost:3000/auth/google

GET {{google}}